require 'find'

namespace :build do
  desc 'Build README.md'
  task :readme do

    def build_markdown_examples
      ruby_file_name = 'example.rb'
      template_file_name = 'template.md'
      Find.find('.') do |path|
        next unless File.directory?(path)
        Dir.chdir(path) do
          if File.exist?(ruby_file_name) && File.exist?(template_file_name)
            system("ruby #{ruby_file_name} > output.txt")
            system("markdown_helper include --pristine #{template_file_name} example.md")
          end
        end
      end
    end

    def build_readme
      system('markdown_helper include --pristine template.md readme.md')
    end

    dir = File.dirname(__FILE__)
    Dir.chdir(dir) do
      build_markdown_examples
      build_readme
    end
  end
end